# EasyPanel monorepo configuration - Minimal approach
# Let Nixpacks auto-detect packages and use simple start command

[start]
cmd = 'if [ "$SERVICE_TYPE" = "frontend" ]; then cd frontend && npm ci && npm run build && npm run preview -- --host 0.0.0.0 --port $PORT; elif [ "$SERVICE_TYPE" = "worker" ]; then cd worker && python worker.py; else cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT; fi'